services:
  grafana:
    image: grafana/grafana:10.4.3
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      # datasource & dashboards provisioning
      - ./crypto-price-pipeline/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - postgres
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: airflow
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  airflow:
    image: apache/airflow:2.7.1
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@postgres:5432/airflow
      AIRFLOW__LOGGING__LOG_LEVEL: INFO
      AIRFLOW__SCHEDULER__FILE_PROCESSOR_PROCESS_TIMEOUT: "120"
      AIRFLOW__WEBSERVER__WEB_SERVER_WORKER_TIMEOUT: "300"
      AIRFLOW_CONN_CRYPTO_DB: postgresql://postgres:postgres@postgres:5432/crypto
      CRYPTO_COINS: bitcoin,ethereum,solana,binancecoin
      VS_CURRENCY: usd
      # dbt env for the BashOperator (matches profiles.yml in the starter)
      DBT_HOST: postgres
      DBT_PORT: 5432
      DBT_DB: crypto
      DBT_USER: postgres
      DBT_PASSWORD: postgres
      # ensure the needed libs are installed in the Airflow image at start
      _PIP_ADDITIONAL_REQUIREMENTS: |
        pandas
        openpyxl
        psycopg2-binary
        apache-airflow-providers-postgres
        pyarrow
        requests
        dbt-core==1.7.12
        dbt-postgres==1.7.12
        great_expectations==0.18.12
    volumes:
      - ./online-retail-etl:/opt/airflow/dags/online-retail-etl
      - ./nyc-taxi-etl:/opt/airflow/dags/nyc-taxi-etl
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./crypto-price-pipeline/airflow/dags:/opt/airflow/dags/crypto-price-pipeline
      - ./crypto-price-pipeline/dbt:/opt/airflow/dbt
      - ./earthquakes-rt/airflow/dags:/opt/airflow/dags/earthquakes-rt
      - ./earthquakes-rt/data:/opt/airflow/data
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command: >
      bash -c "airflow db init &&
               airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin &&
               airflow scheduler & airflow webserver"
volumes:
  postgres-data:
