services:
  spark-master:
    image: apache/spark:3.5.1
    container_name: spark-master
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master", "--host", "spark-master"]
    ports:
      - "7077:7077"
      - "8081:8080"     # Spark Master UI → http://localhost:8081
    volumes:
      - "C:\\Users\\a\\OneDrive\\Desktop\\Data-Engineering-projects\\earthquakes-rt\\spark:/opt/spark-apps"
      - "C:\\Users\\a\\OneDrive\\Desktop\\Data-Engineering-projects\\earthquakes-rt\\data:/opt/data"

  spark-worker:
    image: apache/spark:3.5.1
    container_name: spark-worker
    depends_on:
      - spark-master
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
    volumes:
      - "C:\\Users\\a\\OneDrive\\Desktop\\Data-Engineering-projects\\earthquakes-rt\\spark:/opt/spark-apps"
      - "C:\\Users\\a\\OneDrive\\Desktop\\Data-Engineering-projects\\earthquakes-rt\\data:/opt/data"
