crypto_profile:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_HOST') }}"
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      port: "{{ env_var('DBT_PORT', '5432') }}"
      dbname: "{{ env_var('DBT_DB', 'crypto') }}"
      schema: public
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10
      search_path: "public,bronze,silver,gold"
