apiVersion: 1

datasources:
  - name: Postgres (crypto)
    type: postgres
    access: proxy
    url: postgres:5432
    database: crypto
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: "disable"
      postgresVersion: 1300
      timescaledb: false
